version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "15432:5432"
    volumes:
      - /opt/postgre/data:/var/lib/postgresql/data
    networks: 
      - postgres-compose-network
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "localhost@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on: 
      - postgres-compose
    networks: 
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
